#import Day_2.tip_calculator
#import Day_3.treasure_island
#import Day_4.rock_paper_scissors
#import Day_5.pasword_generator
#import Day_7.Hangman_game
#import Day_8.caesar_cipher
#import Day_9.blind_auction
#import Day_10.Calculator
#import Day_11.blackjack
#import Day_12.guess_number
#import Day_14.higher_lower_game
import Day_15.coffee_machine